### ISSUE TITLE
当_meta中的值为空时, 不添加到inventory中

### ISSUE THREAD

**Issue by AnyISalIn** [Little-gg/kree#2]
# Example
```json
"{"appserver":"192.168.20.141",
  "dbserver":"192.168.20.149",
  "_meta":
  {"192.168.20.141":
    {"ansible_ssh_pass":"","ansible_ssh_user":""},
    "192.168.20.149":{"ansible_ssh_pass":"","username":""}
    }
}"
```

![image](https://cloud.githubusercontent.com/assets/16937838/19991244/d1868164-a26e-11e6-879b-a6a44ecd7aa3.png)

**Comment by Little-gg** [comment]
fix code: https://github.com/Little-gg/kree/commit/d964719583d96541f7776ed5cc6a2f6d1d15171d
